version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.9.3
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - "9201:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash
    volumes:
      - ./logstash/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch